import { type BrowserSession } from "../../lib/supabase-auth";
import { type Announcement, type AnnouncementDraft } from "../../models/announcements/announcement";
import { createAnnouncement, listManagementAnnouncements, updateAnnouncement } from "../../repositories/announcements/announcement-repository";

export function announcementDefaults(): AnnouncementDraft { const visibleFrom = berlinNow(); return { titel: "", inhalt_html: "<p></p>", sichtbar_ab: visibleFrom, sichtbar_bis: addBerlinMonths(visibleFrom, 1), sort_order: null, aktiv: true }; }
export async function loadAnnouncementsManagement(session: BrowserSession): Promise<Announcement[]> { const rows = await listManagementAnnouncements(session); return rows.sort((left, right) => { const difference = (left.sort_order ?? Number.MAX_SAFE_INTEGER) - (right.sort_order ?? Number.MAX_SAFE_INTEGER); return difference || String(right.sichtbar_ab ?? "").localeCompare(String(left.sichtbar_ab ?? "")) || String(left.titel ?? "").localeCompare(String(right.titel ?? ""), "de", { sensitivity: "base" }) || left.id - right.id; }); }
export function normalizeAndValidateAnnouncement(draft: AnnouncementDraft, existingActive?: boolean): { payload?: Omit<Announcement, "id">; error?: string } { const title = draft.titel?.trim() ?? ""; const html = draft.inhalt_html?.trim() ?? ""; const sortOrder = draft.sort_order === null || draft.sort_order === undefined ? null : Number(draft.sort_order); if (!title) return { error: "Titel ist erforderlich." }; if (!html) return { error: "HTML-Inhalt ist erforderlich." }; if (draft.sichtbar_ab && draft.sichtbar_bis && draft.sichtbar_bis < draft.sichtbar_ab) return { error: "Das Sichtbarkeitsende darf nicht vor dem Beginn liegen." }; if (sortOrder !== null && !Number.isInteger(sortOrder)) return { error: "Die Sortierreihenfolge muss eine ganze Zahl sein." }; return { payload: { titel: title, inhalt_html: html, sichtbar_ab: draft.sichtbar_ab || null, sichtbar_bis: draft.sichtbar_bis || null, sort_order: sortOrder, aktiv: existingActive ?? true } }; }
export const saveAnnouncement = (session: BrowserSession, id: number | null, payload: Omit<Announcement, "id">) => id === null ? createAnnouncement(session, payload) : updateAnnouncement(session, id, payload);
export const setAnnouncementActive = (session: BrowserSession, id: number, active: boolean) => updateAnnouncement(session, id, { aktiv: active });
function berlinNow() { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Berlin", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date()).reduce<Record<string, string>>((result, part) => { result[part.type] = part.value; return result; }, {}); return `${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}`; }
function addBerlinMonths(value: string, months: number) { const date = new Date(`${value}:00Z`); date.setUTCMonth(date.getUTCMonth() + months); return date.toISOString().slice(0, 16); }
