import { useCallback, useEffect, useState } from "react";
import { type BrowserSession } from "../../lib/supabase-auth";
import { useEditLock } from "../../lib/use-edit-lock";
import { type Announcement, type AnnouncementDraft } from "../../models/announcements/announcement";
import { announcementDefaults, deactivateAnnouncement, loadAnnouncementsManagement, normalizeAndValidateAnnouncement, removeAnnouncement, saveAnnouncement } from "../../services/announcements/announcement-service";
import { AnnouncementEditorPanel } from "./AnnouncementEditorPanel";

export function AnnouncementManagement({ session, canEdit, onBack }: { session: BrowserSession; canEdit: boolean; onBack: () => void }) {
  const [items, setItems] = useState<Announcement[]>([]); const [selectedId, setSelectedId] = useState<number | null>(null); const [creating, setCreating] = useState(false); const [draft, setDraft] = useState<AnnouncementDraft>({}); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(() => loadAnnouncementsManagement(session).then(setItems).catch((cause: Error) => { setMessage(cause.message); return [] as Announcement[]; }), [session]);
  useEffect(() => { void load(); }, [load]); const selected = items.find((item) => item.id === selectedId) ?? null; const selectedIndex = selected ? items.findIndex((item) => item.id === selected.id) : -1; const editLock = useEditLock(session, "bekanntmachung", selected?.id, Boolean(selected && canEdit && !creating));
  useEffect(() => { if (!creating) queueMicrotask(() => setDraft(selected ?? announcementDefaults())); }, [selected, creating]); useEffect(() => { if (editLock.message) queueMicrotask(() => setMessage(editLock.message)); }, [editLock.message]);
  function startNew() { setCreating(true); setSelectedId(null); setDraft(announcementDefaults()); setMessage(""); } function selectEntry(id: number) { setCreating(false); setSelectedId(id); setMessage(""); } function moveSelection(offset: number) { const target = items[selectedIndex + offset]; if (target) selectEntry(target.id); } function set(key: keyof Announcement, value: string | number | boolean | null) { setDraft((current) => ({ ...current, [key]: value })); }
  async function save() { const validation = normalizeAndValidateAnnouncement(draft); if (!validation.payload) { setMessage(validation.error ?? "Ungültige Bekanntmachung."); return; } if (!creating && !editLock.acquired) { setMessage(editLock.message || "Die Bearbeitungssperre wird noch geprüft."); return; } setSaving(true); setMessage(""); try { const rows = await saveAnnouncement(session, creating ? null : selected?.id ?? null, validation.payload); const savedId = rows[0]?.id ?? selected?.id ?? null; await load(); setCreating(false); setSelectedId(savedId); setMessage("Bekanntmachung gespeichert."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Bekanntmachung konnte nicht gespeichert werden."); } finally { setSaving(false); } }
  async function deactivate() { if (!selected) return; if (!editLock.acquired) { setMessage(editLock.message || "Die Bearbeitungssperre wird noch geprüft."); return; } if (!window.confirm(`Die Bekanntmachung „${selected.titel ?? "Ohne Titel"}“ wirklich deaktivieren?`)) return; setSaving(true); setMessage(""); try { await deactivateAnnouncement(session, selected.id); await load(); setMessage("Bekanntmachung wurde deaktiviert."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Bekanntmachung konnte nicht deaktiviert werden."); } finally { setSaving(false); } }
  async function remove() { if (!selected) return; if (!editLock.acquired) { setMessage(editLock.message || "Die Bearbeitungssperre wird noch geprüft."); return; } if (!window.confirm(`Die Bekanntmachung „${selected.titel ?? "Ohne Titel"}“ endgültig löschen?`)) return; setSaving(true); setMessage(""); try { await removeAnnouncement(session, selected.id); setSelectedId(null); setCreating(false); await load(); setMessage("Bekanntmachung wurde gelöscht."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Bekanntmachung konnte nicht gelöscht werden."); } finally { setSaving(false); } }
  return <section className="data-workspace announcement-management"><div className="data-toolbar"><div className="editor-actions"><button className="secondary-action" onClick={onBack}>Zur Startseite</button><button className="secondary-action" onClick={() => void load()}>Aktualisieren</button></div><span>{items.length} Bekanntmachungen</span>{canEdit && <button onClick={startNew}>Bekanntmachung anlegen</button>}</div>{message && <p className="notice" role="status">{message}</p>}<div className="split-view"><div className="data-table-wrap"><table><thead><tr><th>Sortierung</th><th>Titel</th><th>Sichtbar</th><th>Status</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className={selected?.id === item.id && !creating ? "selected-row" : ""} onClick={() => selectEntry(item.id)}><td>{item.sort_order ?? "–"}</td><td><strong>{item.titel}</strong><small>{plainText(item.inhalt_html).slice(0, 100)}</small></td><td>{formatDate(item.sichtbar_ab)} – {formatDate(item.sichtbar_bis)}</td><td>{item.aktiv ? "aktiv" : "inaktiv"}</td></tr>)}</tbody></table>{items.length === 0 && <p className="empty-state">Keine Bekanntmachungen vorhanden.</p>}</div><AnnouncementEditorPanel selected={selected} selectedIndex={selectedIndex} itemCount={items.length} creating={creating} draft={draft} canEdit={canEdit} saving={saving} onChange={set} onMove={moveSelection} onSave={() => void save()} onDeactivate={() => void deactivate()} onRemove={() => void remove()} onClose={() => { setCreating(false); setSelectedId(null); setMessage(""); }} /></div></section>;
}
function formatDate(value: string | null | undefined) { return value ? new Intl.DateTimeFormat("de-DE", { dateStyle: "medium" }).format(new Date(value)) : "–"; } function plainText(value: string | null) { return (value ?? "").replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim(); }
