import { useState } from "react";
import { type MaintenanceContractDraft, maintenanceWorkHoursEffect } from "../../models/maintenance/maintenance-contract";

export function MaintenanceContractEditor({ draft, existing, saving, message, onSave, onCancel }: { draft: MaintenanceContractDraft; existing: boolean; saving: boolean; message: string; onSave: (draft: MaintenanceContractDraft) => void; onCancel: () => void }) {
  const [value, setValue] = useState(draft);
  const effect = maintenanceWorkHoursEffect(value);
  const setEffect = (next: "none" | "credit" | "exempt") => setValue({ ...value, exemptsFromDutyHours: next === "exempt", workHoursCredit: next === "credit" ? Math.max(value.workHoursCredit, 1) : 0 });
  return <section className="data-workspace maintenance-editor"><div className="detail-title"><div><h2>{existing ? "Wartungsvertrag bearbeiten" : "Wartungsvertrag anlegen"}</h2><p>Titel, Kontingent, Arbeitsstundenwirkung und Aktivstatus</p></div></div>{message && <p className="notice">{message}</p>}<fieldset disabled={saving}><label>Titel<input value={value.title} onChange={(event) => setValue({ ...value, title: event.target.value })}/></label><label>Bereich<input value={value.area ?? ""} onChange={(event) => setValue({ ...value, area: event.target.value })}/></label><label>Max. aktive Zuordnungen<input type="number" min="1" value={value.maxActiveAssignments} onChange={(event) => setValue({ ...value, maxActiveAssignments: Math.max(1, Number(event.target.value) || 1) })}/></label><fieldset><legend>Arbeitsstunden-Anrechnung</legend><label><input type="radio" checked={effect === "none"} onChange={() => setEffect("none")}/> Keine Anrechnung</label><label><input type="radio" checked={effect === "credit"} onChange={() => setEffect("credit")}/> Feste Stundengutschrift</label><label><input type="radio" checked={effect === "exempt"} onChange={() => setEffect("exempt")}/> Vollständige Befreiung</label>{effect === "credit" && <label>Gutschrift pro Saison<input type="text" inputMode="decimal" value={String(value.workHoursCredit).replace(".", ",")} onChange={(event) => setValue({ ...value, workHoursCredit: Number(event.target.value.replace(",", ".")) || 0 })}/></label>}</fieldset><label className="wide">Beschreibung<textarea value={value.description ?? ""} onChange={(event) => setValue({ ...value, description: event.target.value })}/></label><label className="wide">Bemerkung<textarea value={value.note ?? ""} onChange={(event) => setValue({ ...value, note: event.target.value })}/></label><label className="check"><input type="checkbox" checked={value.active} onChange={(event) => setValue({ ...value, active: event.target.checked })}/> Vertrag aktiv</label></fieldset><div className="editor-actions"><button disabled={saving} onClick={() => onSave(value)}>{saving ? "Speichert …" : "Speichern"}</button><button className="secondary-action" onClick={onCancel}>Abbrechen</button></div></section>;
}
