import { useCallback, useEffect, useState } from "react";
import { type BrowserSession } from "../../lib/supabase-auth";
import { useEditLock } from "../../lib/use-edit-lock";
import { type Appointment, type AppointmentDraft } from "../../models/appointments/appointment";
import { appointmentDefaults, deactivateAppointment, loadAppointmentsManagement, normalizeAndValidateAppointment, removeAppointment, saveAppointment } from "../../services/appointments/appointment-service";
import { AppointmentEditorPanel } from "./AppointmentEditorPanel";

export function AppointmentManagement({ session, canEdit, onBack }: { session: BrowserSession; canEdit: boolean; onBack: () => void }) {
  const [items, setItems] = useState<Appointment[]>([]); const [selectedId, setSelectedId] = useState<number | null>(null); const [creating, setCreating] = useState(false); const [draft, setDraft] = useState<AppointmentDraft>({}); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(() => loadAppointmentsManagement(session).then(setItems).catch((cause: Error) => { setMessage(cause.message); return [] as Appointment[]; }), [session]);
  useEffect(() => { void load(); }, [load]); const selected = items.find((item) => item.id === selectedId) ?? null; const selectedIndex = selected ? items.findIndex((item) => item.id === selected.id) : -1; const editLock = useEditLock(session, "termin", selected?.id, Boolean(selected && canEdit && !creating));
  useEffect(() => { if (!creating) queueMicrotask(() => setDraft(selected ?? appointmentDefaults())); }, [selected, creating]); useEffect(() => { if (editLock.message) queueMicrotask(() => setMessage(editLock.message)); }, [editLock.message]);
  function startNew() { setCreating(true); setSelectedId(null); setDraft(appointmentDefaults()); setMessage(""); } function selectEntry(id: number) { setCreating(false); setSelectedId(id); setMessage(""); } function moveSelection(offset: number) { const target = items[selectedIndex + offset]; if (target) selectEntry(target.id); } function set(key: keyof Appointment, value: string | boolean | null) { setDraft((current) => ({ ...current, [key]: value })); }
  async function save() { const validation = normalizeAndValidateAppointment(draft); if (!validation.payload) { setMessage(validation.error ?? "Ungültiger Termin."); return; } if (!creating && !editLock.acquired) { setMessage(editLock.message || "Die Bearbeitungssperre wird noch geprüft."); return; } setSaving(true); setMessage(""); try { const rows = await saveAppointment(session, creating ? null : selected?.id ?? null, validation.payload); const savedId = rows[0]?.id ?? selected?.id ?? null; await load(); setCreating(false); setSelectedId(savedId); setMessage("Termin gespeichert."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Termin konnte nicht gespeichert werden."); } finally { setSaving(false); } }
  async function deactivate() { if (!selected) return; if (!editLock.acquired) { setMessage(editLock.message || "Die Bearbeitungssperre wird noch geprüft."); return; } if (!window.confirm(`Den Termin „${selected.titel ?? "Ohne Titel"}“ wirklich deaktivieren?`)) return; setSaving(true); setMessage(""); try { await deactivateAppointment(session, selected.id); await load(); setMessage("Termin wurde deaktiviert."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Termin konnte nicht deaktiviert werden."); } finally { setSaving(false); } }
  async function remove() { if (!selected) return; if (!editLock.acquired) { setMessage(editLock.message || "Die Bearbeitungssperre wird noch geprüft."); return; } if (!window.confirm(`Den Termin „${selected.titel ?? "Ohne Titel"}“ endgültig löschen?`)) return; setSaving(true); setMessage(""); try { await removeAppointment(session, selected.id); setSelectedId(null); setCreating(false); await load(); setMessage("Termin wurde gelöscht."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Termin konnte nicht gelöscht werden."); } finally { setSaving(false); } }
  return <section className="data-workspace appointment-management"><div className="data-toolbar"><div className="editor-actions"><button className="secondary-action" onClick={onBack}>Zur Startseite</button><button className="secondary-action" onClick={() => void load()}>Aktualisieren</button></div><span>{items.length} Termine</span>{canEdit && <button onClick={startNew}>Termin anlegen</button>}</div>{message && <p className="notice" role="status">{message}</p>}<div className="split-view"><div className="data-table-wrap"><table><thead><tr><th>Datum</th><th>Zeit</th><th>Titel</th><th>Sichtbarkeit</th><th>Status</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className={selected?.id === item.id && !creating ? "selected-row" : ""} onClick={() => selectEntry(item.id)}><td>{formatDate(item.datum)}</td><td>{formatTimeRange(item.start_uhrzeit, item.end_uhrzeit)}</td><td><strong>{item.titel}</strong></td><td>{formatDate(item.sichtbar_ab)} – {formatDate(item.sichtbar_bis)}</td><td>{item.aktiv ? "aktiv" : "inaktiv"}</td></tr>)}</tbody></table>{items.length === 0 && <p className="empty-state">Keine Termine vorhanden.</p>}</div><AppointmentEditorPanel selected={selected} selectedIndex={selectedIndex} itemCount={items.length} creating={creating} draft={draft} canEdit={canEdit} saving={saving} onChange={set} onMove={moveSelection} onSave={() => void save()} onDeactivate={() => void deactivate()} onRemove={() => void remove()} onClose={() => { setCreating(false); setSelectedId(null); setMessage(""); }} /></div></section>;
}
function formatDate(value: string | null | undefined) { return value ? new Intl.DateTimeFormat("de-DE", { dateStyle: "medium" }).format(new Date(value)) : "–"; } function formatTimeRange(start: string | null, end: string | null) { return [start, end].filter(Boolean).join(" – ") || "–"; }
