-- Parzellenprotokolle bleiben von den operativen Ablesungen getrennt.
-- Eine neu erfasste oder übernommene Ablesung wird nur referenziert und als
-- Snapshot im Protokoll festgehalten; die historische Ablesung selbst wird nie verändert.

create table if not exists public.parzellen_protokoll (
    id bigint generated by default as identity primary key,
    parzelle_id bigint not null references public.parzelle(id),
    mitglied_id bigint references public.mitglied(id),
    protokoll_typ text not null check (protokoll_typ in ('uebernahme', 'rueckgabe', 'begehung')),
    protokoll_datum date not null default current_date,
    status text not null default 'entwurf' check (status in ('entwurf', 'abgeschlossen')),
    vorstand_mitglied_id bigint references public.mitglied(id),
    vorstand2_mitglied_id bigint references public.mitglied(id),
    begleitperson_mitglied_id bigint references public.mitglied(id),
    begleitperson_name text,
    anlass text,
    zustand_bemerkung text,
    vereinbarung text,
    dokument_id bigint references public.dokument(id),
    paechter_signiert_am timestamptz,
    begleitperson_signiert_am timestamptz,
    vorstand1_signiert_am timestamptz,
    vorstand2_signiert_am timestamptz,
    erstellt_am timestamptz not null default now(),
    erstellt_von uuid,
    abgeschlossen_am timestamptz,
    abgeschlossen_von uuid,
    updated_at timestamptz not null default now()
);

create index if not exists ix_parzellen_protokoll_parzelle_datum
    on public.parzellen_protokoll (parzelle_id, protokoll_datum desc);
create index if not exists ix_parzellen_protokoll_mitglied
    on public.parzellen_protokoll (mitglied_id);

create table if not exists public.parzellen_protokoll_ablesung (
    id bigint generated by default as identity primary key,
    protokoll_id bigint not null references public.parzellen_protokoll(id) on delete cascade,
    medium text not null check (medium in ('strom', 'wasser')),
    zaehler_id bigint references public.zaehler(id),
    ablesung_id bigint references public.zaehler_ablesung(id),
    quelle text not null check (quelle in ('neu_abgelesen', 'letzte_uebernommen')),
    ablesedatum timestamp without time zone not null,
    zaehlernummer text,
    stand numeric not null check (stand >= 0),
    foto_pfad text,
    foto_dateiname text,
    foto_drive_file_id text,
    unique (protokoll_id, medium)
);

create table if not exists public.parzellen_begehung_feststellung (
    id bigint generated by default as identity primary key,
    protokoll_id bigint not null references public.parzellen_protokoll(id) on delete cascade,
    bereich text,
    feststellung text not null,
    frist date,
    status text not null default 'offen' check (status in ('offen', 'erledigt')),
    erledigt_am timestamptz,
    bemerkung text
);

create index if not exists ix_parzellen_begehung_feststellung_offen
    on public.parzellen_begehung_feststellung (status, frist)
    where status = 'offen';

grant select, insert, update, delete on table public.parzellen_protokoll to authenticated;
grant select, insert, update, delete on table public.parzellen_protokoll_ablesung to authenticated;
grant select, insert, update, delete on table public.parzellen_begehung_feststellung to authenticated;

grant usage, select on sequence public.parzellen_protokoll_id_seq to authenticated;
grant usage, select on sequence public.parzellen_protokoll_ablesung_id_seq to authenticated;
grant usage, select on sequence public.parzellen_begehung_feststellung_id_seq to authenticated;
