-- G7.1: Ein User darf ausschließlich eine eigene, noch ungeprüfte Arbeitsstunde erfassen.
-- Verwaltungs- und Prüfprozesse bleiben unverändert und werden in späteren G7-Schritten überarbeitet.
drop policy if exists arbeitsstunde_insert_own_open on public.arbeitsstunde;
create policy arbeitsstunde_insert_own_open on public.arbeitsstunde
  for insert to authenticated
  with check (
    public.current_mitglied_id() is not null
    and mitglied_id = public.current_mitglied_id()
    and status = 'offen'
    and freigegeben = false
    and genehmigt_von is null
    and genehmigt_am is null
    and (
      not public.is_demo_or_reviewer()
      or public.is_demo_mitglied_id(mitglied_id)
    )
  );

-- Der Verlauf bestand bereits in der Live-Datenbank, war aber nicht versioniert.
-- Bekannte Einschränkungen bis G7.4:
-- * ON DELETE CASCADE bewahrt keinen dauerhaften Löschverlauf.
-- * SELECT/INSERT für alle authenticated ist für eine Audit-Tabelle zu offen.
-- G7.4 ersetzt diese Übergangsstruktur durch einen gehärteten, atomaren Prüfworkflow.
create table if not exists public.arbeitsstunde_pruefverlauf (
  id bigint generated by default as identity primary key,
  arbeitsstunde_id integer not null,
  aktion text not null default '',
  begruendung text not null default '',
  geprueft_von integer not null default 0,
  geprueft_am timestamp without time zone not null default now(),
  vorher_snapshot text not null default '',
  nachher_snapshot text null
);

alter table public.arbeitsstunde_pruefverlauf
  add column if not exists arbeitsstunde_id integer,
  add column if not exists aktion text not null default '',
  add column if not exists begruendung text not null default '',
  add column if not exists geprueft_von integer not null default 0,
  add column if not exists geprueft_am timestamp without time zone not null default now(),
  add column if not exists vorher_snapshot text not null default '',
  add column if not exists nachher_snapshot text null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint c
    join pg_class r on r.oid = c.conrelid
    join pg_namespace n on n.oid = r.relnamespace
    where n.nspname = 'public'
      and r.relname = 'arbeitsstunde_pruefverlauf'
      and c.contype = 'f'
      and c.confrelid = 'public.arbeitsstunde'::regclass
  ) then
    alter table public.arbeitsstunde_pruefverlauf
      add constraint arbeitsstunde_pruefverlauf_arbeitsstunde_id_fkey
      foreign key (arbeitsstunde_id)
      references public.arbeitsstunde(id)
      on delete cascade;
  end if;
end;
$$;

alter table public.arbeitsstunde_pruefverlauf enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'arbeitsstunde_pruefverlauf'
      and policyname = 'arbeitsstunde_pruefverlauf_select_authenticated'
  ) then
    create policy arbeitsstunde_pruefverlauf_select_authenticated
      on public.arbeitsstunde_pruefverlauf
      for select to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'arbeitsstunde_pruefverlauf'
      and policyname = 'arbeitsstunde_pruefverlauf_insert_authenticated'
  ) then
    create policy arbeitsstunde_pruefverlauf_insert_authenticated
      on public.arbeitsstunde_pruefverlauf
      for insert to authenticated
      with check (true);
  end if;
end;
$$;

grant select, insert on table public.arbeitsstunde_pruefverlauf to authenticated;

do $$
begin
  if to_regclass('public.arbeitsstunde_pruefverlauf_id_seq') is not null then
    grant usage, select on sequence public.arbeitsstunde_pruefverlauf_id_seq to authenticated;
  end if;
end;
$$;
