-- Grundlage für den revisionsfähigen Jahresabschluss.
-- Der Bestand ist derzeit ein Einvereins-Modell; deshalb wird bewusst kein
-- nicht existentes verein_id nachgerüstet.

alter table public.parzellen_belegung
    add column if not exists beendigungsgrund text;

alter table public.parzellen_belegung
    drop constraint if exists parzellen_belegung_beendigungsgrund_chk;

alter table public.parzellen_belegung
    add constraint parzellen_belegung_beendigungsgrund_chk
    check (beendigungsgrund is null or beendigungsgrund in ('kuendigung', 'tod', 'wechsel', 'sonstiges'));

create table if not exists public.kostenart (
    id bigint generated by default as identity primary key,
    bezeichnung text not null,
    beschreibung text,
    aktiv boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint kostenart_bezeichnung_uq unique (bezeichnung)
);

create table if not exists public.umlageart (
    id bigint generated by default as identity primary key,
    kuerzel text not null,
    bezeichnung text not null,
    verteilung text not null,
    aktiv boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint umlageart_kuerzel_uq unique (kuerzel),
    constraint umlageart_verteilung_chk check (verteilung in (
        'pro_mitglied', 'pro_flaeche_und_tag', 'anschluss_und_tag',
        'verbrauch', 'einzel', 'keine'
    ))
);

insert into public.umlageart (kuerzel, bezeichnung, verteilung)
values
    ('U1', 'Umlage pro Mitglied', 'pro_mitglied'),
    ('U2', 'Umlage nach Fläche und Belegungstagen', 'pro_flaeche_und_tag'),
    ('U-S', 'Strom-Grundkosten nach Anschluss und Belegungstagen', 'anschluss_und_tag'),
    ('U-W', 'Wasser-Grundkosten nach Anschluss und Belegungstagen', 'anschluss_und_tag'),
    ('V-S', 'Stromverbrauch', 'verbrauch'),
    ('V-W', 'Wasserverbrauch', 'verbrauch'),
    ('EINZEL', 'Einzelkosten', 'einzel'),
    ('KEINE', 'Keine Weiterverteilung', 'keine')
on conflict (kuerzel) do update
set bezeichnung = excluded.bezeichnung,
    verteilung = excluded.verteilung,
    updated_at = now();

create table if not exists public.jahresabschluss (
    id bigint generated by default as identity primary key,
    saison_id integer not null references public.saison(id),
    status text not null default 'in_bearbeitung',
    berechnung_version text not null default '1',
    bemerkung text,
    erstellt_am timestamp with time zone not null default now(),
    erstellt_von bigint references public.mitglied(id),
    abgeschlossen_am timestamp with time zone,
    abgeschlossen_von bigint references public.mitglied(id),
    constraint jahresabschluss_saison_uq unique (saison_id),
    constraint jahresabschluss_status_chk check (status in ('in_bearbeitung', 'berechnet', 'geprueft', 'abgeschlossen')),
    constraint jahresabschluss_abschluss_chk check (
        (status = 'abgeschlossen' and abgeschlossen_am is not null and abgeschlossen_von is not null)
        or status <> 'abgeschlossen'
    )
);

create table if not exists public.jahresabschluss_rechnung (
    id bigint generated by default as identity primary key,
    saison_id integer not null references public.saison(id),
    lieferant text not null,
    rechnungsnummer text,
    rechnungsdatum date not null,
    leistungs_von date,
    leistungs_bis date,
    gesamtbetrag numeric(12,2) not null check (gesamtbetrag >= 0),
    bemerkung text,
    erstellt_am timestamp with time zone not null default now(),
    erstellt_von bigint references public.mitglied(id),
    constraint jahresabschluss_rechnung_leistungszeitraum_chk check (
        leistungs_von is null or leistungs_bis is null or leistungs_von <= leistungs_bis
    )
);

create table if not exists public.jahresabschluss_rechnung_zuordnung (
    id bigint generated by default as identity primary key,
    rechnung_id bigint not null references public.jahresabschluss_rechnung(id) on delete cascade,
    kostenart_id bigint not null references public.kostenart(id),
    umlageart_id bigint not null references public.umlageart(id),
    betrag numeric(12,2) not null check (betrag > 0),
    parzelle_id bigint references public.parzelle(id),
    mitglied_id bigint references public.mitglied(id),
    bemerkung text,
    created_at timestamp with time zone not null default now()
);

create table if not exists public.jahresabschluss_position (
    id bigint generated by default as identity primary key,
    jahresabschluss_id bigint not null references public.jahresabschluss(id) on delete cascade,
    parzelle_id bigint references public.parzelle(id),
    mitglied_id bigint references public.mitglied(id),
    position_typ text not null,
    menge numeric(14,4),
    einheit text,
    preis numeric(14,6),
    betrag numeric(12,2) not null,
    bemerkung text,
    created_at timestamp with time zone not null default now()
);

create table if not exists public.jahresabschluss_verbrauch (
    id bigint generated by default as identity primary key,
    jahresabschluss_position_id bigint not null references public.jahresabschluss_position(id) on delete cascade,
    parzelle_id bigint not null references public.parzelle(id),
    mitglied_id bigint references public.mitglied(id),
    zaehler_id bigint not null references public.zaehler(id),
    verbrauchsart text not null check (verbrauchsart in ('strom', 'wasser')),
    von_datum date not null,
    bis_datum date not null,
    zaehlerstand_start numeric(14,3) not null,
    zaehlerstand_ende numeric(14,3) not null,
    verbrauch numeric(14,3) not null,
    grund text not null check (grund in ('normal', 'zaehlerwechsel', 'paechterwechsel', 'zaehlerwechsel_und_paechterwechsel')),
    constraint jahresabschluss_verbrauch_zeitraum_chk check (von_datum <= bis_datum),
    constraint jahresabschluss_verbrauch_stand_chk check (zaehlerstand_ende >= zaehlerstand_start),
    constraint jahresabschluss_verbrauch_menge_chk check (verbrauch >= 0)
);

create table if not exists public.jahresabschluss_vorauszahlung (
    id bigint generated by default as identity primary key,
    saison_id integer not null references public.saison(id),
    mitglied_id bigint not null references public.mitglied(id),
    parzelle_id bigint references public.parzelle(id),
    zahlungsdatum date not null,
    betrag numeric(12,2) not null check (betrag > 0),
    verwendungszweck text,
    erstellt_am timestamp with time zone not null default now(),
    erstellt_von bigint references public.mitglied(id)
);

create table if not exists public.jahresabschluss_korrektur (
    id bigint generated by default as identity primary key,
    ursprungsabschluss_id bigint not null references public.jahresabschluss(id),
    saison_id integer not null references public.saison(id),
    status text not null default 'in_bearbeitung',
    begruendung text not null,
    erstellt_am timestamp with time zone not null default now(),
    erstellt_von bigint references public.mitglied(id),
    abgeschlossen_am timestamp with time zone,
    abgeschlossen_von bigint references public.mitglied(id),
    constraint jahresabschluss_korrektur_status_chk check (status in ('in_bearbeitung', 'berechnet', 'geprueft', 'abgeschlossen'))
);

create table if not exists public.jahresabschluss_korrektur_position (
    id bigint generated by default as identity primary key,
    korrektur_id bigint not null references public.jahresabschluss_korrektur(id) on delete cascade,
    ursprungsposition_id bigint references public.jahresabschluss_position(id),
    parzelle_id bigint references public.parzelle(id),
    mitglied_id bigint references public.mitglied(id),
    position_typ text not null,
    betrag_differenz numeric(12,2) not null,
    bemerkung text
);

create index if not exists jahresabschluss_rechnung_saison_idx on public.jahresabschluss_rechnung(saison_id);
create index if not exists jahresabschluss_position_abschluss_idx on public.jahresabschluss_position(jahresabschluss_id);
create index if not exists jahresabschluss_position_mitglied_idx on public.jahresabschluss_position(mitglied_id);
create index if not exists jahresabschluss_verbrauch_position_idx on public.jahresabschluss_verbrauch(jahresabschluss_position_id);
create index if not exists jahresabschluss_vorauszahlung_saison_mitglied_idx on public.jahresabschluss_vorauszahlung(saison_id, mitglied_id);

create or replace function public.validate_jahresabschluss_rechnung_zuordnung()
returns trigger
language plpgsql
as $$
declare
    v_rechnung_id bigint := coalesce(new.rechnung_id, old.rechnung_id);
    v_gesamtbetrag numeric(12,2);
    v_zugeordnet numeric(12,2);
    v_kuerzel text;
begin
    select r.gesamtbetrag into v_gesamtbetrag
    from public.jahresabschluss_rechnung r
    where r.id = v_rechnung_id;

    select coalesce(sum(z.betrag), 0) into v_zugeordnet
    from public.jahresabschluss_rechnung_zuordnung z
    where z.rechnung_id = v_rechnung_id
      and z.id <> coalesce(old.id, -1);

    if tg_op <> 'DELETE' then
        v_zugeordnet := v_zugeordnet + new.betrag;

        select kuerzel into v_kuerzel
        from public.umlageart
        where id = new.umlageart_id;

        if v_kuerzel = 'EINZEL' and new.parzelle_id is null and new.mitglied_id is null then
            raise exception 'EINZEL-Zuordnungen benötigen eine Parzelle oder ein Mitglied.';
        end if;
    end if;

    if v_zugeordnet > v_gesamtbetrag then
        raise exception 'Die Zuordnungssumme (%) übersteigt den Rechnungsbetrag (%).', v_zugeordnet, v_gesamtbetrag;
    end if;

    if tg_op = 'DELETE' then
        return old;
    end if;

    return new;
end;
$$;

drop trigger if exists trg_validate_jahresabschluss_rechnung_zuordnung on public.jahresabschluss_rechnung_zuordnung;
create trigger trg_validate_jahresabschluss_rechnung_zuordnung
before insert or update or delete on public.jahresabschluss_rechnung_zuordnung
for each row execute function public.validate_jahresabschluss_rechnung_zuordnung();

create or replace function public.prevent_abgeschlossener_jahresabschluss_change()
returns trigger
language plpgsql
as $$
begin
    if old.status = 'abgeschlossen' then
        raise exception 'Ein abgeschlossener Jahresabschluss ist unveränderlich. Verwenden Sie einen Korrekturabschluss.';
    end if;
    return new;
end;
$$;

drop trigger if exists trg_prevent_abgeschlossener_jahresabschluss_change on public.jahresabschluss;
create trigger trg_prevent_abgeschlossener_jahresabschluss_change
before update or delete on public.jahresabschluss
for each row execute function public.prevent_abgeschlossener_jahresabschluss_change();

grant select, insert, update, delete on table
    public.kostenart,
    public.umlageart,
    public.jahresabschluss,
    public.jahresabschluss_rechnung,
    public.jahresabschluss_rechnung_zuordnung,
    public.jahresabschluss_position,
    public.jahresabschluss_verbrauch,
    public.jahresabschluss_vorauszahlung,
    public.jahresabschluss_korrektur,
    public.jahresabschluss_korrektur_position
to authenticated;

grant usage, select on sequence
    public.kostenart_id_seq,
    public.umlageart_id_seq,
    public.jahresabschluss_id_seq,
    public.jahresabschluss_rechnung_id_seq,
    public.jahresabschluss_rechnung_zuordnung_id_seq,
    public.jahresabschluss_position_id_seq,
    public.jahresabschluss_verbrauch_id_seq,
    public.jahresabschluss_vorauszahlung_id_seq,
    public.jahresabschluss_korrektur_id_seq,
    public.jahresabschluss_korrektur_position_id_seq
to authenticated;

alter table public.kostenart enable row level security;
alter table public.umlageart enable row level security;
alter table public.jahresabschluss enable row level security;
alter table public.jahresabschluss_rechnung enable row level security;
alter table public.jahresabschluss_rechnung_zuordnung enable row level security;
alter table public.jahresabschluss_position enable row level security;
alter table public.jahresabschluss_verbrauch enable row level security;
alter table public.jahresabschluss_vorauszahlung enable row level security;
alter table public.jahresabschluss_korrektur enable row level security;
alter table public.jahresabschluss_korrektur_position enable row level security;

create policy kostenart_select_authenticated on public.kostenart for select to authenticated using (true);
create policy kostenart_write_admin on public.kostenart to authenticated using (public.is_admin_or_vorstand()) with check (public.is_admin_or_vorstand());
create policy umlageart_select_authenticated on public.umlageart for select to authenticated using (true);
create policy umlageart_write_admin on public.umlageart to authenticated using (public.is_admin_or_vorstand()) with check (public.is_admin_or_vorstand());

create policy jahresabschluss_admin_full on public.jahresabschluss to authenticated using (public.is_admin_or_vorstand()) with check (public.is_admin_or_vorstand());
create policy jahresabschluss_rechnung_admin_full on public.jahresabschluss_rechnung to authenticated using (public.is_admin_or_vorstand()) with check (public.is_admin_or_vorstand());
create policy jahresabschluss_rechnung_zuordnung_admin_full on public.jahresabschluss_rechnung_zuordnung to authenticated using (public.is_admin_or_vorstand()) with check (public.is_admin_or_vorstand());
create policy jahresabschluss_vorauszahlung_admin_full on public.jahresabschluss_vorauszahlung to authenticated using (public.is_admin_or_vorstand()) with check (public.is_admin_or_vorstand());
create policy jahresabschluss_korrektur_admin_full on public.jahresabschluss_korrektur to authenticated using (public.is_admin_or_vorstand()) with check (public.is_admin_or_vorstand());
create policy jahresabschluss_korrektur_position_admin_full on public.jahresabschluss_korrektur_position to authenticated using (public.is_admin_or_vorstand()) with check (public.is_admin_or_vorstand());

create policy jahresabschluss_position_select_own_or_admin on public.jahresabschluss_position for select to authenticated using (
    public.is_admin_or_vorstand() or mitglied_id = public.current_mitglied_id()
);
create policy jahresabschluss_position_write_admin on public.jahresabschluss_position to authenticated using (public.is_admin_or_vorstand()) with check (public.is_admin_or_vorstand());
create policy jahresabschluss_verbrauch_select_own_or_admin on public.jahresabschluss_verbrauch for select to authenticated using (
    public.is_admin_or_vorstand() or mitglied_id = public.current_mitglied_id()
);
create policy jahresabschluss_verbrauch_write_admin on public.jahresabschluss_verbrauch to authenticated using (public.is_admin_or_vorstand()) with check (public.is_admin_or_vorstand());
