name: ci

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build Core
        run: dotnet build KGV.Core/KGV.Core.csproj -c Release

      - name: Build Infrastructure
        run: dotnet build KGV.Infrastructure/KGV.Infrastructure.csproj -c Release

      - name: Build WPF
        run: dotnet build KGV.Wpf/KGV.Wpf.csproj -c Release

      - name: Build Tests Project
        run: dotnet build KGV.Tests/KGV.Tests.csproj -c Release

      - name: Test
        run: dotnet test KGV.Tests/KGV.Tests.csproj -c Release --no-build
